services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TodoApplication
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # IMPORTANT: inside docker, use host=db and port=5432
      DATABASE_URL: postgresql://postgres:root@db:5432/TodoApplication
    depends_on:
      - db

volumes:
  pgdata:
